### ISSUE TITLE
Colon not allowed in citation key format

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#268]
Using the test release from #266 (representing, I presume, e78de78), a colon specified in the citation key format is not reflected in the generated key. I've tried two different methods:

1. Inserting a colon in between the fields, specifying e.g. `[auth:lower:nopunct]:[year][Title:lower:nopunct:skipwords:select,1,1][0]` in the preferences. This works in the most recent stable release, but not in the test build.
2. Inserting a colon using `prefix`/`postfix`, e.g. `[auth:lower:nopunct][year:prefix,\:][Title:lower:nopunct:skipwords:select,1,1][0]`. This is rejected outright in the preferences (the text is coloured red when the colon is specified as a prefix), and may well be intended behaviour; this also occurs in the stable release.

**Comment by retorquere** [comment]
That should be fixed with http://tempsend.com/5029466BD9 ; I'm running tests on them now.

**Comment by retorquere** [comment]
The second one won't work; colons are reserved as separators, and there's no escaping facility. The first should work with the D9 version at tempsend.

**Comment by adunning** [comment]
That's what I figured. The colon is still missing; see report ID UUBA5S8C in case it's useful.

**Comment by adunning** [comment]
Still no love for the colon in the most recent build; report ID X49HIS2N.

**Comment by retorquere** [comment]
I was publishing the wrong branch; http://tempsend.com/CBDF90B022

**Comment by retorquere** [comment]
I've added UUBA5S8C as a test case to prevent regression

**Comment by adunning** [comment]
That fixes it; thank you!

**Comment by sixtyfive** [comment]
Seeing as quite a few people prefer to use a colon, how about adding a new filter called "prefixcolon". That way, no escaping facility would be required at all and the colon would still not appear in the case of an empty field... just an idea.

**Comment by retorquere** [comment]
Could you please open a new issue for this idea? Closed issues tend to fall off my radar.

**Comment by retorquere** [comment]
@sixtyfive : the `prefix` filter does just this by using it as `:prefix,\:`

**Comment by adunning** [comment]
Thanks for that!

**Comment by sixtyfive** [comment]
Remember, I knew that because we talked about it ;)
Thanks again though, still being a happy user here!

**Comment by retorquere** [comment]
Fair enough; in that case, you may feel free to interpret it as "already
possible, does not warrant separate implementation" :)
