### ISSUE TITLE
Error exporting with BetterBibTex

### ISSUE THREAD

**Issue by tgrigera** [ZotPlus/zotero-better-bibtex#421]
Hi. I'm trying to export my library, but I get an "error on exporting selected file" message.

I first tried clearing the translators as suggested on Zotero's support forum.  After this, BetterBibTex was not listed as export format, I tried Zotero's natibe BibTex export and it worked.  I disabled / reenabled BetterBibTex, BetterBibTex was again an export format.  I tried it and it failed again.  It fails with every item I try to export.  Perhaps the cause is some entry with bad data (I recently imported an old .bib), but I have no clue where to look (I have 800+ items).  Thanks in advance.

Report  ID: 8RPGKMEW

**Comment by tgrigera** [comment]
Update: further tests show the problem only arises when I check the "export files" box.

**Comment by retorquere** [comment]
Thanks for the additional detail; tests are running on the fix. Clearing the translators would have removed BBT, but BBT re-installs the translators every time it starts up, so it auto-corrects itself.

**Comment by tgrigera** [comment]
Thanks for the quick response. I later discovered I can do without the file export, since the links to the Zotero attached files are actually all I need.  Good to know a fix is on the way, anyhow.

**Comment by retorquere** [comment]
Could you give https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.22-travis-2323.xpi
 a spin to see if the problem is fixed for you?

**Comment by tgrigera** [comment]
Fixed! Many thanks indeed.

**Comment by mullenkamp** [comment]
Hello,

I still get this error when attempting to export a file/collection. I'm using version 1.6.24 on Debian with Zotero Standalone. The normal bibtex export works fine.

Thanks.

**Comment by retorquere** [comment]
Can you enable extended debugging, export again, and submit an error
report?

**Comment by mullenkamp** [comment]
I created a more appropriate new issue in Github and removed it from this closed issue (after reading your support recommendations). Sorry for the confusion.
Here's the issue: https://github.com/ZotPlus/zotero-better-bibtex/issues/425
